server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ademirsantosjr/dio_bootcamp_microservice_springcloud
                default-label: main
